version: "2"

services:
  apache:
    build:
      context: .
      dockerfile: apache.Dockerfile
    networks:
      - apache-mariadb
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/var/www/html:ro
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: mariadb.Dockerfile
      args:
        DBUSER: user
        DBPASS: userpass
        DBADMINUSER: root
        DBADMINPASS: toor
        DBNAME: mydb
    networks:
      - apache-mariadb
    volumes:
      - "./mariadb_data:/var/lib/mysql"
    restart: on-failure

networks:
  apache-mariadb: